name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: snok/install-poetry@v1.5.1
      - name: Install test dependencies
        run: poetry install -v
        shell: bash
      - name: Test
        run: poetry run pytest
        shell: bash
